### ISSUE TITLE
the proposed method used in CT images

### ISSUE THREAD

**Issue by GuobinZhangTJU** [yulequan/UA-MT#11]
Hi, thanks for your sharing.
Did you do research in CT image segmentation using your proposed method? I try to run your coder on CT dataset but the performance is not very well.
Many tkanks,

**Comment by yulequan** [comment]
I have not tried our method on CT images. But it should also work since it is a general framework, not especially designed for MRI. For CT datasets, maybe you need to take care of the processing step.
