### ISSUE TITLE
Could you please share the Atrial Segmentation Challenge dataset with me?

### ISSUE THREAD

**Issue by xzhws** [yulequan/UA-MT#4]
Hi @yulequan,
I want to try your method with  Atrial Segmentation Challenge dataset. However, it seems that I could not download the training and testing dataset since  the Data Access Agreement Form was closed in http://atriaseg2018.cardiacatlas.org/. I wonder whether you still have this dataset and could you please share it with me? 

Best regards!

Zhiqiang

**Comment by yulequan** [comment]
Hi Zhiqiang,

You can contact the challenge organizer for requesting the dataset.
