### ISSUE TITLE
Why is the student model stored instead of a teacher model?

### ISSUE THREAD

**Issue by chuxiang93** [yulequan/UA-MT#8]
Dear @yulequan 
      Another question, why is the student model stored instead of a teacher model in the training phase. In the paper of "Mean Teacher", I found that the teacher model has better performance.
`if iter_num % 1000 == 0:
      save_mode_path = os.path.join(snapshot_path, 'iter_' + str(iter_num) + '.pth')
      torch.save(model.state_dict(), save_mode_path)
      logging.info("save model to {}".format(save_mode_path))`
Thanks, 
Jianqiang Ma

**Comment by yulequan** [comment]
Hi @mjq93, In our experiment. The student model and teacher model achieve similar performance. Therefore, we both use student model for final evaluation.

**Comment by chuxiang93** [comment]
OK, I know, thank you for your reply.
