### ISSUE TITLE
Could you tell me something about the datasets,thanks!

### ISSUE THREAD

**Issue by TakashimaZakuro** [yulequan/UA-MT#9]

**Comment by TakashimaZakuro** [comment]
Hello! I've read your paper and very like it. So, I try to run your code. But the challeng of the MRI segmentation has been closed, so I cannot get the datasets. So could you tell me how can I get the datasets? Is it suitable to let you to send the datasets to me directly? Thank you very much!

**Comment by zs963048949** [comment]
> Hello! I've read your paper and very like it. So, I try to run your code. But the challeng of the MRI segmentation has been closed, so I cannot get the datasets. So could you tell me how can I get the datasets? Is it suitable to let you to send the datasets to me directly? Thank you very much!

did you obtain the datasets？Could you send me directly？Thanks

**Comment by zenglilililili** [comment]
Please share with me, thank you!  E-mail :zenglihhu@163.com

**Comment by zs963048949** [comment]
no....




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zengli"<notifications@github.com&gt;; 
发送时间: 2020年10月6日(星期二) 晚上9:33
收件人: "yulequan/UA-MT"<UA-MT@noreply.github.com&gt;; 
抄送: "凌乱 ~ 华丽"<963048949@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yulequan/UA-MT] Could you tell me something about the datasets,thanks! (#9)





 
Please share with me, thank you!  E-mail :zenglihhu@163.com

**Comment by TakashimaZakuro** [comment]
I haven't get the datasets. The website of the datasets seems to have crashed. If who can get the datasets, I hope he can share with us QAQ. Thanks very much!

**Comment by yulequan** [comment]
Hi @zenglilililili @zs963048949 @TakashimaZakuro ,

I have got permission to share the datasets and uploaded our processed h5 data in the data folder. You can check it. Please consider citing the summary paper when you use the LA segmentation data.
